name: Auto-publish new versions!

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    name: Publish new versions!
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish new version release!
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
